name: bankingMicroservices

services:
  postgres: 
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: BANK
    ports:
      - "5432:5432"    
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:6.2.6-v19
    container_name: redis
    environment:
       REDIS_ARGS: "--requirepass admin1234"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data

  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    ports:
       - "9094:9094"
    environment:
       - KAFKA_CFG_NODE_ID=1
       - KAFKA_CFG_PROCESS_ROLES=controller,broker
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_KRAFT_CLUSTER_ID=CLUSTER_ID_1
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=localCluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka     

volumes:
  postgres_data:
  redis_data:

           
